import os, re
def esc(s): return s.replace('\\', '\\\\').replace("'", "\\'")
hp = os.path.join(os.environ['USERPROFILE'], 'Desktop', 'travel_scenic_rag')
fp = os.path.join(hp, 'static', 'index.html')
L = []
L.append('<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>旅途小智 - 旅游景点智能助手</title><style>')
L.append(':root{--primary:#2563eb;--primary-dark:#1d4ed8;--primary-light:#dbeafe;--teal:#0d9488;--bg:#f0f4f8;--surface:#fff;--text:#1e293b;--text2:#64748b;--muted:#94a3b8;--border:#e2e8f0;--shadow:0 4px 12px rgba(0,0,0,0.08)}')
L.append('*{margin:0;padding:0;box-sizing:border-box}')
L.append('body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;background:var(--bg);height:100vh;display:flex;flex-direction:column;color:var(--text);line-height:1.6}')
L.append('.header{background:linear-gradient(135deg,#1e40af 0%,#0d9488 100%);color:#fff;padding:16px 24px;display:flex;align-items:center;gap:14px;flex-shrink:0;box-shadow:0 2px 12px rgba(0,0,0,0.15)}')
L.append('.header::after{content:"";position:absolute;bottom:-1px;left:0;right:0;height:3px;background:linear-gradient(90deg,#60a5fa,#2dd4bf,#60a5fa);opacity:.6}')
L.append('.header-icon{width:40px;height:40px;border-radius:10px;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center;font-size:20px;flex-shrink:0}')
L.append('.header-c{flex:1;min-width:0}.header-c h1{font-size:18px;font-weight:700;letter-spacing:.5px}.header-c .sub{font-size:12px;opacity:.85;margin-top:1px}')
L.append('.h-acts{display:flex;gap:8px;flex-shrink:0}')
L.append('.h-btn{width:36px;height:36px;border:none;border-radius:8px;background:rgba(255,255,255,.15);color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:16px;transition:all .2s}')
L.append('.h-btn:hover{background:rgba(255,255,255,.25);transform:scale(1.05)}')
L.append('#CC{flex:1;overflow-y:auto;padding:20px 0;scroll-behavior:smooth}')
L.append('#CC::-webkit-scrollbar{width:6px}#CC::-webkit-scrollbar-track{background:transparent}#CC::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:3px}')
L.append('.msgs{max-width:720px;margin:0 auto;padding:0 20px}')
L.append('.msg{margin-bottom:16px;display:flex;animation:fi .3s ease}')
L.append('@keyframes fi{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}')
L.append('.msg.u{justify-content:flex-end}.msg.a{justify-content:flex-start}')
L.append('.ma{width:32px;height:32px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:14px;margin-top:4px}')
L.append('.msg.u .ma{order:1;margin-left:10px;background:linear-gradient(135deg,#2563eb,#1d4ed8);color:#fff}')
L.append('.msg.a .ma{margin-right:10px;background:linear-gradient(135deg,#0d9488,#0f766e);color:#fff}')
L.append('.mb{max-width:75%;min-width:0}')
L.append('.bb{padding:12px 16px;border-radius:16px;line-height:1.65;font-size:14px;word-break:break-word}')
L.append('.msg.u .bb{background:linear-gradient(135deg,#2563eb,#3b82f6);color:#fff;border-bottom-right-radius:4px;box-shadow:0 2px 8px rgba(37,99,235,.2)}')
L.append('.msg.a .bb{background:var(--surface);color:var(--text);border-bottom-left-radius:4px;box-shadow:var(--shadow);border:1px solid var(--border)}')
L.append('.mt{font-size:11px;color:var(--muted);margin-top:4px;padding:0 4px}.msg.u .mt{text-align:right}')
L.append('.tm{justify-content:center;margin-bottom:4px;margin-top:-8px}')
L.append('.tm .bb{background:#f1f5f9;color:var(--text2);font-size:12px;padding:6px 14px;border-radius:20px;display:inline-flex;align-items:center;gap:6px;border:1px solid #e2e8f0}')
L.append('.ts{width:12px;height:12px;border:2px solid #e2e8f0;border-top-color:var(--primary);border-radius:50%;animation:sp .7s linear infinite;display:inline-block;flex-shrink:0}')
L.append('@keyframes sp{to{transform:rotate(360deg)}}')
L.append('.td{display:inline-flex;gap:3px;align-items:center;padding:4px 0}')
L.append('.td span{width:6px;height:6px;border-radius:50%;background:var(--muted);animation:dp 1.4s ease-in-out infinite}')
L.append('.td span:nth-child(2){animation-delay:.2s}.td span:nth-child(3){animation-delay:.4s}')
L.append('@keyframes dp{0%,80%,100%{transform:scale(.6);opacity:.4}40%{transform:scale(1);opacity:1}}')
L.append('.msg.a .bb strong{font-weight:600;color:#0f172a}')
L.append('.msg.a .bb code{background:#f1f5f9;color:#7c3aed;padding:1px 5px;border-radius:4px;font-size:13px}')
L.append('.msg.a .bb pre{background:#1e293b;color:#e2e8f0;padding:12px 16px;border-radius:8px;overflow-x:auto;font-size:13px;margin:8px 0}')
L.append('.msg.a .bb pre code{background:transparent;color:inherit;padding:0}')
L.append('.msg.a .bb hr{border:none;border-top:1px solid var(--border);margin:12px 0}')
L.append('.msg.a .bb table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px}')
L.append('.msg.a .bb th,.msg.a .bb td{border:1px solid var(--border);padding:6px 10px;text-align:left}')
L.append('.msg.a .bb th{background:#f8fafc;font-weight:600}')
L.append('.msg.a .bb ul,.msg.a .bb ol{padding-left:20px;margin:6px 0}')
L.append('.msg.a .bb h3,.msg.a .bb h4{margin:12px 0 6px;font-weight:600}')
L.append('.msg.a .bb h3{font-size:15px;color:#0f172a}')
L.append('.cu::after{content:"\\u258C";animation:bl .8s step-end infinite;color:var(--primary)}')
L.append('@keyframes bl{50%{opacity:0}}')
L.append('.ia{border-top:1px solid var(--border);background:var(--surface);padding:12px 20px;flex-shrink:0;box-shadow:0 -2px 8px rgba(0,0,0,.04)}')
L.append('.ir{max-width:720px;margin:0 auto;display:flex;gap:8px;align-items:flex-end}')
L.append('.ir input{flex:1;padding:12px 18px;border:1px solid var(--border);border-radius:24px;font-size:14px;outline:none;transition:all .2s;background:var(--bg);color:var(--text)}')
L.append('.ir input:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(37,99,235,.1);background:#fff}')
L.append('.ir button{width:44px;height:44px;border:none;border-radius:50%;background:linear-gradient(135deg,var(--primary),var(--primary-dark));color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:all .2s;box-shadow:0 2px 8px rgba(37,99,235,.3)}')
L.append('.ir button:hover{transform:scale(1.05);box-shadow:0 4px 12px rgba(37,99,235,.4)}')
L.append('.ir button:disabled{background:#cbd5e1;box-shadow:none;cursor:not-allowed;transform:none}')
L.append('.ir button svg{width:18px;height:18px;fill:#fff}')
L.append('.wl{text-align:center;padding:70px 20px 40px;animation:fi .5s ease}')
L.append('.wi{width:72px;height:72px;border-radius:50%;background:linear-gradient(135deg,#dbeafe,#ccfbf1);display:flex;align-items:center;justify-content:center;font-size:34px;margin:0 auto 20px;box-shadow:0 4px 16px rgba(37,99,235,.15)}')
L.append('.wl h2{font-size:20px;font-weight:700;margin-bottom:8px}')
L.append('.wl p{font-size:14px;color:var(--text2);line-height:1.8;max-width:420px;margin:0 auto}')
L.append('.ex{display:flex;flex-wrap:wrap;gap:10px;justify-content:center;margin-top:24px}')
L.append('.ex button{padding:10px 18px;border:1px solid var(--border);border-radius:20px;background:var(--surface);color:var(--text2);font-size:13px;cursor:pointer;transition:all .2s;font-family:inherit}')
L.append('.ex button:hover{border-color:var(--primary);color:var(--primary);background:var(--primary-light);transform:translateY(-1px)}')
L.append('@media(max-width:600px){.header{padding:12px 16px}.header-icon{width:34px;height:34px;font-size:17px}.header-c h1{font-size:16px}.msgs{padding:0 12px}.mb{max-width:85%}.bb{padding:10px 14px}.ia{padding:10px 12px}.wl{padding:50px 16px 30px}.wi{width:60px;height:60px;font-size:28px}.ex button{padding:8px 14px;font-size:12px}}')
L.append('</style></head><body>')
L.append('<div class="header"><div class="header-icon">\\u26FA</div><div class="header-c"><h1>旅途小智</h1><div class="sub">旅游景点智能问答 \\u00B7 支持景点、天气、美食、行程规划</div></div><div class="h-acts"><button class="h-btn" onclick="clearChat()" title="新建对话">\\u2795</button></div></div>')
L.append('<div id="CC"><div class="msgs" id="msgs"><div class="wl" id="wl"><div class="wi">\\u26FA</div><h2>欢迎使用旅途小智</h2><p>我是一个旅游景点咨询助手。<br>可以帮你查询景点信息、天气、美食，规划行程。</p><div class="ex"><button onclick="sendEx(\'北京有哪些5A景点？\')">北京5A景点</button><button onclick="sendEx(\'杭州有什么免费景点推荐？\')">杭州免费景点</button><button onclick="sendEx(\'成都天气怎么样？\')">成都天气</button><button onclick="sendEx(\'帮我规划3天的北京行程\')">规划行程</button></div></div></div></div>')
L.append('<div class="ia"><div class="ir"><input id="inp" type="text" placeholder="输入你的问题..." autofocus><button id="sbtn" onclick="sendMsg()" disabled><svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg></button></div></div>')
L.append('<script>var tid=null,st=false,ms=document.getElementById("msgs"),wl=document.getElementById("wl"),inp=document.getElementById("inp"),sbtn=document.getElementById("sbtn"),cc=document.getElementById("CC");')
L.append('inp.oninput=function(){sbtn.disabled=!this.value.trim()||st};')
L.append('inp.onkeydown=function(e){if(e.key=="Enter"&&!e.shiftKey&&this.value.trim()&&!st){e.preventDefault();sendMsg()}};')
L.append('function sendEx(t){inp.value=t;sbtn.disabled=false;sendMsg()}')
L.append('function clr(){if(st)return;tid=null;ms.innerHTML=\'<div class="wl" id="wl"><div class="wi">\\u26FA</div><h2>欢迎使用旅途小智</h2><p>我是一个旅游景点咨询助手。<br>可以帮你查询景点信息、天气、美食，规划行程。</p><div class="ex"><button onclick="sendEx(\\\'北京有哪些5A景点？\\\')">北京5A景点</button><button onclick="sendEx(\\\'杭州有什么免费景点推荐？\\\')">杭州免费景点</button><button onclick="sendEx(\\\'成都天气怎么样？\\\')">成都天气</button><button onclick="sendEx(\\\'帮我规划3天的北京行程\\\')">规划行程</button></div></div>\';document.getElementById("wl").style.display="";inp.focus()}')
L.append('function ts(){var d=new Date();return("0"+d.getHours()).slice(-2)+":"+("0"+d.getMinutes()).slice(-2)}')
L.append('function addMsg(r,h){wl.style.display="none";var d=document.createElement("div");d.className="msg "+(r=="u"?"u":"a");var av=(r=="u")?"👤":"\\u26FA";d.innerHTML="<div class=\\\"ma\\\">"+av+"</div><div class=\\\"mb\\\"><div class=\\\"bb\\\">"+h+"</div><div class=\\\"mt\\\">"+ts()+"</div></div>";ms.appendChild(d);sb();return d.querySelector(".bb")}')
L.append('function addTool(t){wl.style.display="none";var d=document.createElement("div");d.className="msg tm";d.innerHTML="<div class=\\\"bb\\\"><span class=\\\"ts\\\"></span>"+t+"</div>";ms.appendChild(d);sb();return d}')
L.append('function sb(){cc.scrollTop=cc.scrollHeight}')
L.append('function md(s){if(!s)return"";s=s.replace(/./g,function(c){if(c=="&")return"&amp;";if(c=="<")return"&lt;";if(c==">")return"&gt;";return c});s=s.replace(/\\*\\*(.+?)\\*\\*/g,"<strong>$1</strong>");s=s.replace(/`(.+?)`/g,"<code>$1</code>");s=s.replace(/^### (.+)$/gm,"<h3>$1</h3>");s=s.replace(/^(\\d+)\\. (.+)$/gm,"<li>$2</li>");s=s.replace(/^- (.+)$/gm,"<li>$1</li>");s=s.replace(/\\|(.+)\\|/g,function(m){var c=m.slice(1,-1).split("|").map(function(x){return x.trim()});if(c.length<2)return m;if(/^-+$/.test(c[0]))return"";return"<tr>"+c.map(function(x,i){var t=i==0?"th":"td";return"<"+t+">"+x+"</"+t+">"}).join("")+"</tr>"});s=s.replace(/(<tr>.*<\\/tr>\\n?)+/g,"<table>$&</table>");s=s.replace(/\\n{2,}/g,"\\n");return s}')
L.append('async function sendMsg(){var t=inp.value.trim();if(!t||st)return;inp.value="";sbtn.disabled=true;st=true;addMsg("u",esc(t));var td=addTool("正在检索...");var bb=addMsg("a",\'<span class="td"><span></span><span></span><span></span></span>\');var fa="";try{var r=await fetch("/api/agent/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,thread_id:tid})});if(!r.ok){var e=await r.json().catch(function(){return{detail:r.statusText}});var b=ms.lastElementChild.querySelector(".bb");if(b)b.innerHTML="<span style=\\\"color:#dc2626\\\">抱歉，出错了："+esc(e.detail||e.message||"未知错误")+"</span>";return}var h=r.headers.get("X-Thread-Id");if(h)tid=h;var rd=r.body.getReader(),dc=new TextDecoder(),buf="";while(true){var g=await rd.read();if(g.done)break;buf+=dc.decode(g.value,{stream:true});var ps=buf.split("\\n\\n");buf=ps.pop()||"";for(var pi=0;pi<ps.length;pi++){var bl=ps[pi],ls=bl.split("\\n"),ev="",ds="";for(var li=0;li<ls.length;li++){var ll=ls[li].trim();if(ll.startsWith("event: "))ev=ll.slice(7).trim();else if(ll.startsWith("data: "))ds=ll.slice(6)}if(!ds)continue;try{var da=JSON.parse(ds);if(ev==="tool_start"){var tn=da.name||"";var lb={scenic_spot_search:"查询景点数据库",get_weather:"查询天气",search_food:"搜索美食",plan_itinerary:"规划行程",exchange_rate:"汇率计算"};td.innerHTML=\'<div class="bb"><span class="ts"></span>\'+(lb[tn]||"调用"+tn)+"</div>"}else if(ev==="tool_end"){if(td.parentNode)td.remove()}else if(ev==="token"){fa+=da.text||"";bb.innerHTML=md(fa)+\'<span class="cu"></span>\';sb()}else if(ev==="done"){if(da.thread_id)tid=da.thread_id;if(fa)bb.innerHTML=md(fa);else bb.innerHTML="<span style=\\\"color:var(--muted)\\\">暂无回答</span>"}else if(ev==="error"){bb.innerHTML="<span style=\\\"color:#dc2626\\\">抱歉，出错了："+esc(da.error||"")+"</span>"}}catch(e2){}}}}catch(e3){var b2=ms.lastElementChild.querySelector(".bb");if(b2)b2.innerHTML="<span style=\\\"color:#dc2626\\\">网络错误，请检查连接后重试。</span>"}st=false;sbtn.disabled=!inp.value.trim();inp.focus()}')
L.append('function esc(s){if(!s)return"";var r="";for(var i=0;i<s.length;i++){var c=s[i];if(c=="&")r+="&amp;";else if(c=="<")r+="&lt;";else if(c==">")r+="&gt;";else if(c=="\\n")r+="<br>";else r+=c}return r}')
L.append('</script></body></html>')
html = '\n'.join(L)
html = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), html)
with open(fp, 'w', encoding='utf-8') as f: f.write(html)
print('OK', os.path.getsize(fp), 'bytes')
os.remove(__file__)
